### ISSUE TITLE
Automatically start a new container when a node inside a service is marked as DOWN.

### ISSUE THREAD

**Issue by deviantony** [rems/docker-helloworld#2]
First part of the dynamic-scaling process.

Check http://www.consul.io/docs/agent/watches.html

**Comment by rems** [comment]
Even if not available yet, https://atlas.hashicorp.com/features/maintain seems good.

Consul already provides support for other tools from atlas http://www.consul.io/docs/guides/atlas.html

**Comment by deviantony** [comment]
I've came up with a solution in Consul. 

The Consul node must be in charge of restarting a node via a watch handler script. For the moment, a simple handler script written in bash is listing every services in 'warning' state and for each of them it kills the associated Docker container and restart a new one.

See the following configuration of the CRN stack:

https://github.com/deviantony/docker-CRN/tree/helloworld-health-check
